# Vew Travis CI configuration
#Thanks to @yshalsager

sudo: required

services:
  - docker

before_install:
  # Clone DualBootPatcher Repository
  - git clone --recursive https://github.com/Mysteryagr/DualBootPatcher -b master DualBootPatcher/
  # Pull docker images
  - docker pull yshalsager/dualbootpatcher:9.3.0-4-base
  - docker pull yshalsager/dualbootpatcher:9.3.0-4-android
  - docker pull yshalsager/dualbootpatcher:9.3.0-4-linux

script:
  # Make work directories 
  - mkdir $HOME/.android
  - mkdir -p DualBootPatcher/builder/ && cd DualBootPatcher/
  # Build APK
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/builder/DualBootPatcher:rw,z" -v "${HOME}/.android:/builder/.android:rw,z" Mysteryagr/dualbootpatcher:9.3.0-4-android bash << EOF
    cd DualBootPatcher/builder && cmake .. -DMBP_BUILD_TARGET=android -DMBP_BUILD_TYPE=debug && make -j16 && rm -rf assets && cpack && make apk -j16
    make android-system_armeabi-v7a -j16 && make -C data/devices -j16
    exit
    EOF
  - |
    docker run --rm -i -e USER_ID=$(id -u) -e GROUP_ID=$(id -g) -v "$(pwd):/builder/DualBootPatcher:rw,z" -v "${HOME}/.android:/builder/.android:rw,z" Mysteryagr/dualbootpatcher:9.3.0-4-linux bash << EOF
    # Build Utilities Zip
    cd ~/DualBootPatcher/builder && ./utilities/create.sh
    # Build Linux
    cmake .. -DMBP_BUILD_TARGET=desktop -DMBP_PORTABLE=ON && make -j16 && cpack
    exit
    EOF

deploy:
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_RAHMYAPK"
  file: "$PWD/Mysteryagr/DualBootPatcher/Android_GUI/build/outputs/apk/Android_GUI-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true

after_success:
  - export TRAVIS_CURRENT_DATE=$(date +"%d%m%y-%Hh%Mm")
  # Check output & md5sum
  - ls -l /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
  - md5sum /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/Android_GUI/build/outputs/apk/debug/Android_GUI-debug.apk
  - ls -l /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/builder/utilities/DualBootUtilities-9.3.0.zip
  - md5sum /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/builder/utilities/DualBootUtilities-9.3.0.zip
  - ls -l /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/builder/DualBootPatcher-9.3.0-Linux.zip
  - md5sum /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/builder/DualBootPatcher-9.3.0-Linux.zip
  # Upload to transfer.sh
  - cd /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/Android_GUI/build/outputs/apk/debug/ &&  curl --upload-file ./Android_GUI-debug.apk https://transfer.sh/Android_GUI-debug-${TRAVIS_CURRENT_DATE}.apk
  - cd /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/builder/utilities/ && curl --upload-file ./DualBootUtilities-9.3.0.zip https://transfer.sh/DualBootUtilities-9.3.0-${TRAVIS_CURRENT_DATE}.zip
  - cd /home/travis/build/Mysteryagr/DualBootPatcher/DualBootPatcher/builder/ && curl --upload-file ./DualBootPatcher-9.3.0-Linux.zip https://transfer.sh/DualBootPatcher-9.3.0-${TRAVIS_CURRENT_DATE}-Linux.zip
